# As config example taken this file: https://github.com/ogrisel/python-appveyor-demo/blob/master/appveyor.yml
environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\tests\\appveyor\\run_with_env.cmd"

  matrix:

    # Pre-installed Python versions, which Appveyor may upgrade to
    # a later point release.
    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "64"
      WAF_ARGS: ""

    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "32"
      WAF_ARGS: ""

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
      WAF_ARGS: ""

cache:
  # Cache binary Python packages e.g. numpy, pycrypto
  - C:\Users\appveyor\.pip-accel -> tests/requirements.txt
  # 'pip-accel' requires caching of downloaded pip packages.
  - C:\Users\appveyor\AppData\Local\pip -> tests/requirements.txt

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - ECHO "Filesystem root:"
  - ps: "ls \"C:/\""

  - ECHO "Chocolatey tools:"
  - ps: "ls \"C:/Tools\""

  - ECHO "Installed SDKs:"
  - ps: "ls \"C:/Program Files/Microsoft SDKs/Windows\""

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  ### Install the PyInsaller dependencies.

  # Install pip-accel to cache pypi packages and avoid compiling some packages.
  # (numpy or pycrypto take a lot of tome to compile).
  #
  # TODO Use upstream version when windows support is merged.
  # Windows support is not yet merged upstream so use own 'pip-accel' fork:
  #   https://github.com/paylogic/pip-accel/pull/60
  - "%CMD_IN_ENV% pip install git+https://github.com/matysek/pip-accel.git"

  # Install the PyInstaller test dependencies.
  - "%CMD_IN_ENV% pip-accel install --disable-pip-version-check --timeout 5 --retries 2 -r tests/requirements-win.txt"

  # Install PyInstaller into virtualenv.
  - "%CMD_IN_ENV% pip install -e ."

build: none

test_script:
  # Split tests into several subprocesses.
  - "%CMD_IN_ENV% py.test -n 3  --timeout 180 --maxfail 5"
